config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
      end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def last_three_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def index
    users = User.all

    if users
      render json: { status: 'Success', message: 'Users fetched successfully', data: users }, status: :ok
    else
      render json: { status: 'Error', message: 'Failed to fetch users', errors: users.errors }, status: :bad_request
    end
  end

  def show
    user = User.find_by(id: params[:id])

    if user
      render json: { status: 'Success', message: 'User fetched successfully', data: user }, status: :ok
    else
      render json: { status: 'Error', message: 'Failed to fetch user', errors: user.errors }, status: :bad_request
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    @latest_posts = @user.last_three_posts
  end
end

app/views/users/index.html.erb
<div class="flex flex-col gap-2 w-full items-center p-2 users">
  <div>
    <% if user_signed_in? %> 
       <h1 class="text-blue-950"> Hi <%= current_user.name.split.first %> </h1> 
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "px-4 py-2 bg-blue-500 rounded-lg" %> 
    <% else %>
      <%= button_to "Sign in", new_user_session_path, class: "px-4 py-2 bg-blue-500 rounded-lg" %> 
    <% end %>
  </div>

  <% @users.each do |user| %>

    <%= render "shared/user", user: user %>
    

  <% end %>
</div>

app/views/users/show.html.erb
<div class="p-4 flex flex-col gap-8 items-center">

  <%= render "shared/user", user: @user %>
  
  <div class="w-full max-w-md p-2 min-h-min border-2 text-lg font-bold "> <%= @user.bio %> </div>

  <div class="w-full flex flex-col gap-2 items-center">
    <% @latest_posts.each do |post| %>
      <%= render "shared/post", post: post, user: @user %>
    <% end %>
  </div>

  <div>
    <%= link_to "See all Posts", user_posts_path(@user), class: "font-bold bg-violet-300 text-500 px-4 py-2 rounded-full" %>
  </div>

</div>