config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
      end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/views/shared/_comment.html.erb
<div class="border-2 p-4">
  <% comments.each do |comment| %>      
  <div class="flex items-center gap-2">
    <p> <span class="font-bold"> <%= comment.author.name %>: </span> <%= comment.text %> </p>
    <% if comment.author == current_user %>
       <%= button_to "Delete", user_post_comment_path(comment.post.author, comment.post, comment), method: :delete, class: "text-white p-1 hover:bg-red-800 bg-red-500 rounded-full" %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/shared/_post.html.erb
<div class=" flex flex-col gap-4 w-full">
  <%= link_to user_post_path(user, post) do %>

  <div class=" flex flex-col gap-4 w-full max-w-md p-2 min-h-min border-2 ">
    <h2 class="font-bold"> <%= post.title %> </h2>
    <p> <%= post.text %> </p>

    <div class="flex gap-4 w-full justify-end">
      <p>Comments: <%= post.comments_counter %> </p>
      <p>Likes: <%= post.likes_counter %> </p>
    </div>
    
  </div>
  <% end %>
</div>

app/views/shared/_user.html.erb
<div class=" w-full max-w-md bg-violet-300 p-2 min-h-min" >

  <%= link_to user_path(user) do %>
    <div class="flex gap-6 justify-start items-center w-full">

      <div class="h-36 w-36">
        <img src=<%= user.photo %> alt="user image" class="h-full w-full rounded-full object-cover">
      </div>

      <div class="flex flex-col gap-4 px-2 h-24 w-48">
        <h1 class="font-bold text-2xl text-left text-500"><%= user.name %></h1>
        <p class="text-xs text-right text-300">Number of posts: <%= user.posts_counter %></p>
      </div>

    </div>
  <% end %>

</div>