config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
      end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_number

  def last_five_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_number
    author.increment!(:posts_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  skip_before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
    @user = User.includes(:posts).find(params[:user_id])

    if @posts
      render json: { status: 'Success', message: 'Posts fetched successfully', data: @posts }, status: :ok
    else
      render json: { status: 'Error', message: 'Failed to fetch posts!', errors: @posts.errors }, status: :bad_request
    end
  end

  def show
    @post = Post.includes(:author).find_by(author_id: params[:user_id], id: params[:id])
    @user = @post.author

    if @post
      render json: { status: 'Success', message: 'Post fetched successfully', data: @post }, status: :ok
    else
      render json: { status: 'Error', message: 'Failed to fetch post!', errors: @post.errors }, status: :bad_request
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource except: %i[index show]

  def index
    @user = User.find_by(id: params[:user_id])
    @posts = Post.includes(:author).where(author_id: params[:user_id])
  end

  def show
    @post = Post.includes(:author).find_by(author_id: params[:user_id], id: params[:id])
    @user = @post.author
    @comments = Post.find(@post.id).comments
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = Post.new(post_params)
    @post.author_id = @user.id

    if @post.save
      redirect_to user_posts_path(@user), notice: 'Post created successfully!'
    else
      redirect_to user_posts_path(@user), alert: 'Failed to create the post.'
    end
  end

  def destroy
    @user = current_user
    @post = @user.posts.find_by(id: params[:id])

    puts @post.inspect
    if @post.destroy
      redirect_to user_posts_path(@user), notice: 'Post deleted successfully!'
    else
      redirect_to user_posts_path(@user), alert: 'Failed to delete the post.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<div class="p-4 w-full flex flex-col items-center">
  <%= render "shared/user", user:@user %>

  <div class="py-7">

  <div class="w-full flex justify-end">
   <% if @user == current_user && can?(:create, Post) %>
      <%= link_to "New Post", new_user_post_path(@user), class: "hover:bg-violet-500 bg-violet-300 rounded-full py-2 px-4 text-center" %>
    <% end %>  
  </div>

    <% @posts.each do |post| %>
      <div class="flex flex-col py-7 gap-2">
      
        <%= render "shared/post", post: post, user: @user %>

        <div class="w-full flex gap-2">
          
          <% if can? :destroy, post %>
            <%= button_to "Delete", user_post_path(@user, post), method: :delete, class: "text-white p-2 hover:bg-red-800 bg-red-500 rounded-full" %>
          <% end %>

           <% if can? :create, Comment, Like %>
            <%= link_to "Add Comment", new_user_post_comment_path(@user, post), class: "hover:bg-violet-500 bg-violet-300 rounded-full py-2 px-4 text-center" %>

            <%= form_with url: user_post_likes_path(post.author.id, post.id) do |form| %>
              <%= form.submit 'Like', class: "hover:bg-violet-500 bg-violet-300 rounded-full py-2 px-4 text-center" %>
            <% end %>
          <% end %>

        </div>
        
        <% if post.last_five_comments.present? %>
         <% @comments = post.last_five_comments %>
          <%= render "shared/comment", comments: @comments %>
        <% end %>

      </div>

    <% end %>
    
  </div>

</div>

app/views/posts/new.html.erb
<div class="p-4 flex flex-col gap-4 items-center">
  <h2 class="text-bg-950 font-bold">Create a post</h2>

  <%= form_with model: @post, url: user_posts_path(@user), html: { class: "flex flex-col gap-2 items-center" } do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title, required: true, class: "bg-violet-200 rounded-md p-2" %>
    </div>

    <div>
      <%= f.label :text %>
      <%= f.text_field :text, required: true, class: "bg-violet-200 rounded-md p-2" %>
    </div>

    <div>
      <%= f.submit "Submit", class: "hover:bg-violet-500 bg-violet-300  px-4 py-2 rounded-full" %>
    </div>
  <% end %>

</div>

app/views/posts/show.html.erb
<div class="flex justify-center w-full p-4">

  <div class="flex flex-col w-full gap-4">

    <div class="border-2 p-2">
      
      <div class="flex justify-between">
        <h1 class="font-bold"> <%= @post.title %> </h1>

        <div class="flex gap-2">
          <p>Comments: <%= @post.comments_counter %> </p>
          <p>Likes: <%= @post.likes_counter %> </p>
        </div>
      </div>

      <p class="p-4" > <%= @post.text %> </p>

      <% if can? :destroy, @post %>
            <%= button_to "Delete", user_post_path(@user, @post), method: :delete, class: "text-white p-2 hover:bg-red-800 bg-red-500 rounded-full" %>
          <% end %>

    </div>

    <% if can? :create, @comment, @like %>
      <div class="w-full flex gap-2">
        <%= link_to "Add Comment", new_user_post_comment_path(@post.author.id, @post.id), class: "hover:bg-violet-500  bg-violet-300  rounded-full py-2 px-2 text-center" %>
        <%= form_with url: user_post_likes_path(@post.author.id, @post.id) do |form| %>
          <%= form.submit 'Like', class: "hover:bg-violet-500 bg-violet-300 rounded-full py-2 px-4 text-center" %>
        <% end %>
      </div>
    <% end %>

    <% if @comments.present? %>
          <%= render "shared/comment", comments: @comments %>
    <% end %>

  </div>

</div>